### ISSUE TITLE
ListNav not working with zurb foundation

### ISSUE THREAD

**Issue by sefaaydin** [esteinborn/jquery-listnav#25]
Hello,

I'm using zurb foundaiton 5. My problem :
if I use block-grid then not use listnav. because [class*="block-grid-"] > li { display : block } (line 5066)

How can I use listnav with zurb foundation?
Note : I'm so sorry for my english.

**Comment by esteinborn** [comment]
You'll just need to harden the Css for list nav to overwrite the block class from foundation.
Easiest way would be to add an ID to your list element and prepend all your list av styles with that ID.






On Sun, Feb 8, 2015 at 1:16 PM -0800, "Sefa AYDIN" <notifications@github.com> wrote:












Hello,



I'm using zurb foundaiton 5. My problem :

if I use block-grid then not use listnav. because [class*="block-grid-"] > li { display : block } (line 5066)



How can I use listnav with zurb foundation?

Note : I'm so sorry for my english.

**Comment by esteinborn** [comment]
so an example:
HTML:
```html
<ul id=my-nav" class=listnav">
...
</ul>
```

CSS (SUPER SPECIFIC): 
```css
#my-nav .listNavHide {
  display: none;
}

#my-nav .listNavShow {
  display: list-item;
}
```

or maybe try:
```css
li.listNavHide {
  display: none;
}

li.listNavShow {
  display: list-item;
}
```
